### ISSUE TITLE
How to add filters, and other logger objects from YAML / JSON config?

### ISSUE THREAD

**Issue by selesnow** [s-fleck/lgr#42]
Hello, thank for `lgr`. 

I try add filter to logger confige file, and i can`t do it,  Could you help me?

JSON exampe:
```json
{
"Logger": {
	"threshold": "all",
	"appenders": {
		"AppenderFile": {
			"threshold": "all",
			"file": "special.log",
			"filters": {"my_filter": "function(event) grepl( pattern = 'special', event$custom, ignore.case = TRUE )"}
     }
   }
 }
}
```

And i get: `Error: `f` is not a function with the single argument `event` or an EventFilter, but `function(event) grepl( patte..`. See ?is_filter.`

YAML example:
```yaml
Logger:
  threshold: all
  appenders:
    AppenderFile:
      threshold: all
      file: "special.log"
      filters: "function(event) grepl( pattern = 'special', event$custom, ignore.case = TRUE )"
```
Result: `Error: 'filters' must be a list Filters or a single Filter (see ?is_filter)`

Try next YAML:
```yaml
Logger:
  threshold: all
  appenders:
    AppenderFile:
      threshold: all
      file: "special.log"
      filter: 
        fi: grepl('bird', event$msg)
```

Result: `Error: `f` is not a function with the single argument `event` or an EventFilter, but `grepl('bird', event$msg)`. See ?is_filter.`

And second query: How i can add name of Appender in confige file?
